-d C:\Users\User\Desktop\GOWIN_PROJECT\GOWIN_LABS\fpga_project_2\impl\gwsynthesis\fpga_project_2.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\User\Desktop\GOWIN_PROJECT\GOWIN_LABS\fpga_project_2\src\SaS.cst
-cfg C:\Users\User\Desktop\GOWIN_PROJECT\GOWIN_LABS\fpga_project_2\impl\pnr\device.cfg
-sdc C:\Users\User\Desktop\GOWIN_PROJECT\GOWIN_LABS\fpga_project_2\src\Second.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
